assets: <LIBERO_REPO_ROOT>/libero/libero/assets
bddl_files: <LIBERO_REPO_ROOT>/libero/libero/bddl_files
benchmark_root: <LIBERO_REPO_ROOT>/libero/libero
datasets: <LIBERO_REPO_ROOT>/libero/datasets
init_states: <OFFICIAL_INIT_STATE_ROOT>
